FROM node:20.19.5-bookworm-slim

WORKDIR /app

ARG APP_NAME=@imovel-pratico/api-gateway

ENV APP_NAME=${APP_NAME}
ENV NODE_ENV=production
ENV PORT=3333
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
ENV PNPM_VERSION=10.0.0

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@${PNPM_VERSION} prisma@7.8.0
RUN printf "node-linker=hoisted\nstrict-peer-dependencies=false\n" > .npmrc

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/api-gateway/package.json ./apps/api-gateway/package.json
COPY apps/web-home/package.json ./apps/web-home/package.json
COPY apps/web-admin/package.json ./apps/web-admin/package.json
COPY apps/web-client/package.json ./apps/web-client/package.json
COPY apps/worker-cnd/package.json ./apps/worker-cnd/package.json
COPY apps/worker-registro/package.json ./apps/worker-registro/package.json

COPY packages/database/package.json ./packages/database/package.json
COPY packages/queue/package.json ./packages/queue/package.json

RUN pnpm install --frozen-lockfile --prod=false

COPY . .

RUN printf "node-linker=hoisted\nstrict-peer-dependencies=false\n" > .npmrc
RUN pnpm install --frozen-lockfile --prod=false
RUN prisma generate --schema=packages/database/prisma/schema.prisma
RUN pnpm --filter "${APP_NAME}..." build

EXPOSE 3333

CMD ["sh", "-c", "pnpm --filter ${APP_NAME} start"]
